### ISSUE TITLE
collectorset-controller helm chart broken on new'ish K8s 

### ISSUE THREAD

**Issue by red1dev2** [logicmonitor/k8s-helm-charts#81]
Collectorset-controller and argus helm templates are using a deprecated api endpoint and fails on k8s V: 1.19.3 with an error stating the API version must be updated to rbac.authorization.k8s.io/**v1**

The old api endpoint referanse can be seen in templates/rbac.yml - line 4 

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/**v1beta1**

**Comment by red1dev2** [comment]
The deployment still works just errors out with warnings

**Comment by vkumbhar94** [comment]
> The deployment still works just errors out with warnings

Thanks @red1dev2 for raising PR.
Yes, these are just warnings as rbac.auth* api group has been marked for deprecation.
We have fixed this to create rbac resources with appropriate versions according to k8s cluster version on which chart is being installed. Changes are in LM's CI pipeline, soon it will be released.
